name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
      - name: Checkout
        uses: actions/checkout@v3.2.0
      - name: List Files After
        run: |
          pwd
          ls -a
      - name: Change dir
        run: |
          cd .github
          cd workflows
          ls -a
      - name: Print env var
        run: |
          printenv
      - name: udvalgte env var
        run: |
          echo startenv
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Mr Erik
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
